---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
#

title: FredF Homelab Portal
language: fr
hideVersion: true
hideErrors: true
showStats: true
statusStyle: "dot"
favicon: https://www.fokan.ch/wp-content/uploads/2019/08/fokan_0-1.png
theme: dark # <----- add this line
color: slate # <----- add this line

logo:
  icon: https://www.fokan.ch/wp-content/uploads/2019/08/fokan_0.png 
Proxmox:
  icon: proxmox.png

background: 
#  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80 # <----- add this line
  image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg  
#  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 80 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 80 # 0-100

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
